-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 17:33:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamerecs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamerecs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamerecs` DEFAULT CHARACTER SET utf8 ;
USE `gamerecs` ;

-- -----------------------------------------------------
-- Table `gamerecs`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`User` (
  `User_ID_Steam` VARCHAR(17) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`User_ID_Steam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerecs`.`All_Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`All_Games` (
  `Game_ID` VARCHAR(50) NOT NULL,
  `Game_Tag1` VARCHAR(45) NULL,
  `Game_Tag2` VARCHAR(45) NULL,
  `Game_Tag3` VARCHAR(45) NULL,
  `Player_Count` VARCHAR(45) NULL,
  `Rating_AVG` DOUBLE NULL,
  `Name` VARCHAR(45) NULL,
  `Is_Owned` TINYINT NULL,
  `User_User_ID_Steam` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`Game_ID`, `User_User_ID_Steam`),
  INDEX `fk_All_Games_User1_idx` (`User_User_ID_Steam` ASC) VISIBLE,
  CONSTRAINT `fk_All_Games_User1`
    FOREIGN KEY (`User_User_ID_Steam`)
    REFERENCES `gamerecs`.`User` (`User_ID_Steam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerecs`.`Recommendation_List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`Recommendation_List` (
  `List_ID` VARCHAR(50) NOT NULL,
  `User_User_ID_Steam` VARCHAR(17) NOT NULL,
  `All_Games_Game_ID` VARCHAR(50) NULL,
  `Game_Tag1` VARCHAR(45) NULL,
  `Game_Tag2` VARCHAR(45) NULL,
  `Game_Tag3` VARCHAR(45) NULL,
  `Rating_AVG` DOUBLE NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`List_ID`, `User_User_ID_Steam`),
  INDEX `fk_Recommendation_List_User1_idx` (`User_User_ID_Steam` ASC) VISIBLE,
  INDEX `Game_ID_idx` (`All_Games_Game_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Recommendation_List_User1`
    FOREIGN KEY (`User_User_ID_Steam`)
    REFERENCES `gamerecs`.`User` (`User_ID_Steam`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Game_ID`
    FOREIGN KEY (`All_Games_Game_ID`)
    REFERENCES `gamerecs`.`All_Games` (`Game_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
