-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 22:15:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamerecs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamerecs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamerecs` DEFAULT CHARACTER SET utf8 ;
USE `gamerecs` ;

-- -----------------------------------------------------
-- Table `gamerecs`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`User` (
  `User_ID_Steam` VARCHAR(17) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`User_ID_Steam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerecs`.`Recommendation_List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`Recommendation_List` (
  `List_ID` VARCHAR(50) NOT NULL,
  `User_User_ID_Steam` VARCHAR(17) NOT NULL,
  `Game_ID` VARCHAR(50) NULL,
  `Game_Tag` VARCHAR(45) NULL,
  `Player_Count` VARCHAR(45) NULL,
  `Rating_AVG` DOUBLE NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`List_ID`, `User_User_ID_Steam`),
  INDEX `fk_Recommendation_List_User1_idx` (`User_User_ID_Steam` ASC) VISIBLE,
  CONSTRAINT `fk_Recommendation_List_User1`
    FOREIGN KEY (`User_User_ID_Steam`)
    REFERENCES `gamerecs`.`User` (`User_ID_Steam`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerecs`.`User_has_Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerecs`.`User_has_Game` (
  `User_User_ID_Steam` VARCHAR(17) NOT NULL,
  `Game_Game_ID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`User_User_ID_Steam`, `Game_Game_ID`),
  CONSTRAINT `fk_User_has_Game_User1`
    FOREIGN KEY (`User_User_ID_Steam`)
    REFERENCES `gamerecs`.`User` (`User_ID_Steam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
